AWSTemplateFormatVersion: 2010-09-09
Description: Create Security Groups For Each Env Type
Parameters:
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

  EnvType:
    Description: The Environment Type
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod

Resources:
  DevSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    # Condition: CreateDevSecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22 - Dev Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref SSHLocation

  TestSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    # Condition: CreateTestSecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22 - Test Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref SSHLocation

  ProdSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    # Condition: CreateProdSecurityGroup    
    Properties:
      GroupDescription: Enable SSH access via port 22 - Prod Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref SSHLocation

Outputs:
   DevSecurityGroup:
    # Condition: CreateDevSecurityGroup
    Description: Returns Dev  Security Group 
    Value: !Ref DevSecurityGroup
    Export:
      Name: ExportedSecurityGroup-dev

   TestSecurityGroup:
    # Condition: CreateTestSecurityGroup
    Description: Returns Test Security Group 
    Value: !Ref TestSecurityGroup
    Export:
      Name: ExportedSecurityGroup-test

   ProdSecurityGroup:
    # Condition: CreateProdSecurityGroup
    Description: Returns Prod  Security Group 
    Value: !Ref ProdSecurityGroup
    Export:
      Name: ExportedSecurityGroup-prod                             
  


